apiVersion: v1
kind: Service
metadata:
    name: docker-registry-svc
spec:
    ports:
    - port: 5000
    selector:
        app: docker-registry

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - image: registry:2
          name: docker-registry
          ports:
            - containerPort: 5000
              hostPort: 5000
              name: docker-registry
          volumeMounts:
            - name: docker-registry-persistent-storage
              mountPath: /var/lib/registry
      volumes:
        - name: docker-registry-persistent-storage
          hostPath:
            path: "/home/docker/registry"

      nodeSelector:
        node: "node-06"