apiVersion: v1
kind: Pod
metadata:
    name: healthcheck
    labels: 
        test: healthcheck
spec: 
    restartPolicy: OnFailure
    containers: 
    - name: healthcheck
      image: busybox
      args: 
      - /bin/sh
      - -c
      - sleep 100; exit 1
