apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: httpd
spec:
    replicas: 3
    template:
        metadata:
            labels:
                run: httpd
        spec:
            containers:
                - name: httpd
                  image: httpd:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: httpd-svc
spec:
    type: NodePort
    selector:
        run: httpd
    ports:
      - protocol: TCP
        nodePort: 30000
        port: 8080
        targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: access-httpd
spec:
    podSelector:
        matchLabels:
            run: httpd
    ingress:
        - from:
          - ipBlock:
                cidr: 10.0.12.0/24
          - podSelector:
                matchLabels:
                    access: "true"
          ports:
          - protocol: TCP
            port: 80
