apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 8Gi
    persistentVolumeReclaimPolicy: Retain
    nfs:
        path: /tmp/mysql-pv
        server: 10.0.63.21

