apiVersion: v1
kind: ReplicationController
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: mysql:5
              ports: 
              - containerPort: 3306
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: "123456"
---
apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    ports:
        - port: 3306
    selector: 
        app: mysql

---
apiVersion: v1
kind: ReplicationController
metadata:
    name: myweb
spec:
    replicas: 1
    selector: 
        app: myweb
    template:
        metadata:
            labels:
                app: myweb
        spec:
            containers:
            - name: myweb
              image: kubeguide/tomcat-app:v1
              ports:
              - containerPort: 8080
              env:
              - name: MYSQL_SERVICE_HOST
                value: 'mysql'
              - name: MYSQL_SERVICE_PORT
                value: '3306'
---
apiVersion: v1
kind: Service
metadata:
    name: myweb
spec:
    type: NodePort
    ports:
    - port: 8080
      nodePort: 30009
    selector:
        app: myweb

