apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: nginx-deployment
spec:
    replicas: 3
    template: 
        metadata: 
            labels:
                app: web_server
                run: httpd
        spec: 
            containers:
                - name: nginx
                  image: nginx:1.14.1
                  ports: 
                  - containerPort: 80
