apiVersion: v1
kind: Service
metadata: 
    name: nginx-svc
spec: 
    type: NodePort
    selector:
        run: httpd
    ports: 
    - protocol: TCP
      port: 8080
      nodePort: 30000
      targetPort: 80
